# Generated by Django 5.1.1 on 2024-09-11 17:21

import cloudinary.models
import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[core.validators.validate_image], verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
